import React from "react";
import { Activity, ArrowRight, BadgeCheck, Bot, Braces, CircleAlert, GitCompareArrows, ReceiptText, RotateCcw, ScanLine, ShieldCheck, ShieldX, Sparkles } from "lucide-react";
import { createIntentComparison, createRecoveryGuidance, createVerificationDiff } from "@/lib/security/presentation";
import type { GuardianAiExplanation, GuardianAiRemediation, RiskLevel, TransactionAnalysis } from "@/lib/security/types";
import type { TokenIdentity } from "@shared/tokenIdentity";
type Props = { analysis: TransactionAnalysis; mode: "demo" | "live"; networkName: string; tokenIdentity?: TokenIdentity; aiExplanation?: GuardianAiExplanation; isExplaining?: boolean; onExplain?: () => void; remediation?: GuardianAiRemediation; isRemediating?: boolean; onRemediate?: () => void; onRecover?: () => void };
const profile: Record<RiskLevel, { label: string; message: string; action: string }> = {
  safe: { label: "Clear", message: "No critical deterministic finding was found before signing.", action: "Review the destination" },
  warning: { label: "Review", message: "This request needs a deliberate check before signing.", action: "Pause and verify" },
  critical: { label: "Blocked", message: "Guardian found a permission or intent mismatch.", action: "Reject this request" },
};
function compact(value?: string) { return value ? (value.length > 16 ? `${value.slice(0, 7)}…${value.slice(-5)}` : value) : "—"; }
function human(value: string) { return value.replace(/0x[a-fA-F0-9]{40}/g, (address) => compact(address)); }

export function AnalysisBoard({ analysis, mode, networkName, tokenIdentity, aiExplanation, isExplaining, onExplain, remediation, isRemediating, onRemediate, onRecover }: Props) {
  const { risk, decoded, simulation, reputation, verification, movements, draft, before, after, erc20Evidence } = analysis;
  const state = profile[risk.level]; const movement = movements[0];
  const approval = decoded.kind === "erc20-approval" || decoded.method === "Token operator approval";
  const StateIcon = risk.level === "safe" ? BadgeCheck : risk.level === "warning" ? CircleAlert : ShieldX;
  const intentComparison = createIntentComparison(analysis);
  const recovery = createRecoveryGuidance(analysis);
  const verificationDiff = createVerificationDiff(analysis);
  const expectedEffects = movements.length ? movements.map((item) => `${item.direction === "approval" ? "Permission" : item.direction === "out" ? "Send" : "Receive"} ${item.amount} ${item.symbol}`).join(" · ") : "No explicit decoded asset movement";
  return <article className={`night-review review-${risk.level}`}>
    <section className="confidence-card"><div className="confidence-copy"><div className="night-kicker"><span>{mode === "demo" ? "Guardian demo" : "Live transaction"}</span><i /> <span>{decoded.selector ?? "native transfer"}</span></div><h1>{state.label}</h1><p>{state.message}</p></div><div className="guardian-orbit"><div><StateIcon size={29} strokeWidth={1.9} aria-hidden="true" /><strong>{state.label}</strong><small>review state</small></div></div><div className="confidence-metrics"><div><span>Simulation</span><strong className={`simulation-${simulation.status}`}>{simulation.status === "success" ? "Ready" : simulation.status}</strong></div><div><span>Network</span><strong>{networkName}</strong></div><div><span>Mode</span><strong>{mode === "demo" ? "Sandbox" : "Live"}</strong></div></div></section>
    <section className={`immediate-decision decision-${risk.level}`}><span>Before you sign</span><h2>{expectedEffects}</h2>{tokenIdentity?.registry.status === "listed" && tokenIdentity.registry.logoUri && <div className="token-identity-inline"><img src={tokenIdentity.registry.logoUri} alt="" /><span>{tokenIdentity.registry.name ?? tokenIdentity.registry.symbol} <small>Listed in {tokenIdentity.registry.source}</small></span></div>}<p>{approval ? `To spender ${compact(decoded.spender)}.` : `To ${compact(decoded.recipient ?? decoded.target)}.`} {intentComparison.status === "mismatch" ? "The stated intent does not match this request." : intentComparison.status === "incomplete" ? "Add intent detail before proceeding." : "The stated intent matches the decoded request."}</p><div><small>Intent: <b>{draft.declaredAction || "Not stated"}</b></small><small>Gas: <b>{simulation.gasEstimate ? `${simulation.gasEstimate} units` : "Unavailable"}</b></small></div></section>
    {risk.findings.length > 0 && <section className={`decision-finding finding-${risk.level}`}><strong>{risk.findings[0].title}</strong><p>{risk.findings[0].detail}</p></section>}
    {recovery && <section className="recovery-panel immediate-recovery"><div><span><RotateCcw size={16} aria-hidden="true" /> Next action</span><h2>{recovery.title}</h2><p>{recovery.fix}</p></div><button onClick={onRecover}><RotateCcw size={15} /> Edit & review</button></section>}
    <section className="ai-explanation"><header><div><span><Bot size={16} aria-hidden="true" /> AI explanation</span><small>Bounded by the evidence shown above</small></div><div style={{display: "flex", gap: "8px"}}><button onClick={onExplain} disabled={!onExplain || isExplaining}>{isExplaining ? "Explaining…" : aiExplanation ? "Refresh explanation" : "Explain this review"}</button>{risk.level !== "safe" && <button onClick={onRemediate} disabled={!onRemediate || isRemediating}>{isRemediating ? "Analyzing…" : remediation ? "Refresh suggestions" : "Suggest Safer Alternatives"}</button>}</div></header>{aiExplanation ? <div className="ai-copy"><strong>{aiExplanation.headline}</strong><p>{aiExplanation.explanation}</p><ul>{aiExplanation.questions.map((question) => <li key={question}><Sparkles size={12} className="ai-sparkle" /> <span>{question}</span></li>)}</ul><small>{aiExplanation.source === "ai" ? "AI wording only — risk and signing rules remain deterministic." : "Deterministic fallback — no generated wording was available."}</small></div> : isExplaining ? <div className="ai-copy ai-loading"><div className="skeleton-title"></div><div className="skeleton-text"></div><div className="skeleton-text"></div><div className="skeleton-text short"></div></div> : <p className="ai-empty">Ask Guardian to translate only the decoded call, X Layer simulation result, asset effects, and deterministic findings into direct language.</p>}
    {remediation && <div className="ai-copy" style={{ marginTop: "12px", borderColor: "rgba(239, 68, 68, 0.2)", background: "rgba(239, 68, 68, 0.05)" }}><strong style={{ color: "#F87171" }}>{remediation.headline}</strong><ul>{remediation.advice.map((item, i) => <li key={i} style={{ color: "#FCA5A5" }}><Sparkles size={12} className="ai-sparkle" style={{ color: "#F87171" }} /> <span>{item}</span></li>)}</ul>{remediation.safeAlternative && <p style={{ color: "#FECACA", marginTop: "8px", fontStyle: "italic" }}>Safer Alternative: {remediation.safeAlternative}</p>}</div>}
    {isRemediating && !remediation && <div className="ai-copy ai-loading" style={{ marginTop: "12px" }}><div className="skeleton-title"></div><div className="skeleton-text"></div><div className="skeleton-text"></div></div>}
    </section>
    <details className="review-details"><summary><span>Review details</span><small>Decoded request, checks, and verification evidence</small></summary>
    <section className={`intent-diff intent-${intentComparison.status}`}><header><span><GitCompareArrows size={16} aria-hidden="true" /> {intentComparison.status === "mismatch" ? "Transaction mismatch" : "Intent comparison"}</span><b>{intentComparison.status === "mismatch" ? "Review before signing" : intentComparison.status === "matched" ? "Matches decoded request" : "Intent needed"}</b></header><div><section><small>You intended</small><strong>{intentComparison.intended}</strong></section><section><small>You are signing</small><strong>{intentComparison.actual}</strong></section></div><p>{intentComparison.difference}</p></section>
    <section className="consequence-card"><header><div><span>Signing consequence</span><h2>{approval && decoded.unlimitedApproval ? "Unlimited authority is requested" : decoded.method}</h2></div><div className={`risk-chip chip-${risk.level}`}>{state.action}</div></header><p>{human(decoded.summary)}</p><div className="consequence-route"><div><small>From</small><strong>Your wallet</strong><span>{compact(draft.from)}</span></div><ArrowRight size={17} /><div className={`route-main route-${risk.level}`}><small>{approval ? "Permission" : "Effect"}</small><strong>{approval && decoded.unlimitedApproval ? "Unlimited token access" : movement ? `${movement.amount} ${movement.symbol}` : "Contract interaction"}</strong><span>{approval ? "The spender can move this token later." : "The decoded on-chain effect."}</span></div><ArrowRight size={17} /><div><small>{approval ? "Spender" : "Destination"}</small><strong>{compact(decoded.spender ?? decoded.recipient ?? decoded.target)}</strong><span>{approval ? "Can move assets later" : "Receives the request"}</span></div></div></section>
    <section className="review-grid"><div className="dark-panel effect-panel"><header><span><ScanLine size={15} aria-hidden="true" /> Transaction effect</span><small>Decoded before your wallet opens</small></header><div className="effect-lines"><div><span>Contract</span><strong>{compact(decoded.target)}</strong><small>{decoded.source ?? "Decoded locally"}</small></div><div><span>Expected effect</span><strong>{movement ? `${movement.amount} ${movement.symbol}` : "No asset movement"}</strong><small>{movement ? human(movement.detail) : "No transfer is explicit."}</small></div><div><span>{erc20Evidence ? "Live token evidence" : "Native balance"}</span><strong>{erc20Evidence ? `${erc20Evidence.balance} ${erc20Evidence.symbol}` : `${before[0]?.amount ?? "—"} ${before[0]?.symbol ?? "OKB"}`}</strong><small>{erc20Evidence?.allowance !== undefined ? `Allowance: ${erc20Evidence.allowance} ${erc20Evidence.symbol}` : after.length ? `${after[0]?.amount} ${after[0]?.symbol} after receipt` : "After-state requires trace access"}</small></div>{tokenIdentity && <div className="contract-trust"><span>Contract identity</span><strong>{tokenIdentity.contract.status === "verified" ? "Verified by OKLink" : tokenIdentity.registry.status === "listed" ? "Listed in OKX registry" : "No trusted identity record"}</strong><small>{tokenIdentity.contract.status === "verified" ? `${tokenIdentity.contract.contractName ?? "Contract"}${tokenIdentity.contract.proxy ? " · proxy" : ""}` : tokenIdentity.contract.detail}</small></div>}</div></div>
      <div className="dark-panel finding-panel"><header><span><ShieldCheck size={15} aria-hidden="true" /> Guardian checks</span><small>Deterministic rules</small></header>{risk.findings.length ? <div className="night-findings">{risk.findings.map((finding) => <div key={finding.id} className={`night-finding finding-${finding.level}`}><b>{finding.level}</b><div><strong>{finding.title}</strong><p>{finding.detail}</p></div></div>)}</div> : <div className="night-clear"><BadgeCheck size={16} aria-hidden="true" /><div><strong>No high-risk behavior found</strong><p>Check the destination before approving.</p></div></div>}</div></section>

    <section className="verification-review"><header><div><span><ReceiptText size={16} aria-hidden="true" /> Post-transaction verification</span><small>Expected versus actual; trace scope: wallet-attributed standard ERC-20 transfer assets</small></div><b className={`verification-${verificationDiff.status}`}>{verificationDiff.label}</b></header><div className="verification-diff">{verificationDiff.items.length ? verificationDiff.items.map((item) => <section key={`${item.asset}-${item.symbol}`} className={`verification-item item-${item.outcome}`}><small>{item.symbol} · {item.outcome}</small><strong>Expected {item.expected}</strong><span>Actual {item.actual ?? "not verified"}</span></section>) : <section><small>Actual result</small><strong>Awaiting transaction evidence</strong></section>}</div><p>{verificationDiff.detail}</p></section>
    <section className="evidence-strip"><div><Activity size={15} aria-hidden="true" /><span><b>Reputation</b>{reputation.status === "trusted" ? "Trust signal available" : "No trust assertion"}</span></div><div><BadgeCheck size={15} aria-hidden="true" /><span><b>Receipt</b>{verification.label}</span></div><details><summary><Braces size={14} /> Raw request</summary><code>to: {draft.to}<br />value: {draft.value} wei<br />data: {draft.data}</code></details></section>
    </details>
  </article>;
}
